# -*- coding: utf-8 -*-
"""DV_BetaPhase_MarksChannels.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S4f_JUl9XmcY_hcphqAmYLFnHMYjxDVs
"""

from google.colab import files
import pandas as pd

# Uploading the CSV file and getting the file name
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

df = pd.read_csv('US_videos.csv')
df.head()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

# Sunburst chart

figure = px.sunburst(df, path=['categoryName', 'channelTitle'], values='view_count',
                  title='Sunburst Chart of View Count by Category and Channel')

# Increase the size
figure.update_layout(height=600, width=800)

# Add interactive features
figure.update_layout(margin=dict(l=0, r=0, b=0, t=40))

figure.update_traces(
    hovertemplate='<b>%{label}</b><br>View Count: %{value}<extra></extra>'
)

figure.show()

# Treemap for categories and channel title according to their view_count

fig2 = px.treemap(df, path=['categoryName', 'channelTitle'], values='view_count',
                 title='Treemap of View Count by Category and Channel')
fig2.update_layout(height=700, width=1000)

fig2.show()

# Interactive Scatter Plot
df['trending_date'] = pd.to_datetime(df['trending_date'])
df['publishedAt'] = pd.to_datetime(df['publishedAt'])

# Calculating the number of days a video has been trending by the difference between 'trending_date' and 'publishedAt'
df['days_to_trend'] = (df['trending_date'] - df['publishedAt']).dt.days

# Adding the hovering interactivity to the scatter plot
fig = px.scatter(df, x='view_count', y='likes', size='comment_count', color='categoryName',
                 hover_data=['title', 'days_to_trend'],
                 title='Interactive Scatter Plot', size_max=60)

# Updating the graph size
fig.update_layout(height=800, width=1200)

fig.show()

